apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-booking
  template:
    metadata:
      labels:
        app: order-booking
    spec:
      containers:
      - name: order-booking
        image: saicharan2002/order-booking-image:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-booking-service
spec:
  selector:
    app: order-booking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer